import assert from 'node:assert/strict';
const { runtimeEnv } = await import('../src/env.js');
runtimeEnv.VITE_SUPABASE_URL = 'https://test.example.invalid';
runtimeEnv.VITE_SUPABASE_ANON_KEY = 'test-public-key';
const { supabase, identity, initializeSession, authenticatedHeaders } = await import('../src/session.js');
const { canIdentityWriteCloudCollection, cloudCollections, safeSyncWithCloud } = await import('../src/cloudSync.js');
const user = { id: '11111111-1111-4111-8111-111111111111', email: 'test@example.invalid' };
let member = { company_id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', role: 'Boss', display_name: 'Test', staff_user_id: 'old-staff-id' };
let token = 'user-token';
supabase.auth.getSession = async () => ({ data: { session: token ? { access_token: token, user } : null }, error: null });
supabase.auth.getUser = async () => ({ data: { user }, error: null });
globalThis.fetch = async (url, options) => {
  assert.ok(String(url).includes('user_id=eq.' + user.id));
  assert.ok(String(url).includes('active=eq.true'));
  const headers = new Headers(options.headers);
  assert.equal(headers.get('Authorization'), 'Bearer ' + token);
  return new Response(JSON.stringify(member), { status: 200, headers: { 'content-type': 'application/json' } });
};
await initializeSession();
assert.equal(identity.companyId, member.company_id);
assert.equal(identity.user.userId, 'old-staff-id');
assert.equal(identity.user.role, 'Boss');
const a = (await import('../src/storage.js?companyA')).storageKeys;
token = 'refreshed-user-token';
assert.equal((await authenticatedHeaders()).Authorization, 'Bearer refreshed-user-token');
member = { ...member, company_id: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb' };
await initializeSession();
const b = (await import('../src/storage.js?companyB')).storageKeys;
assert.notEqual(a.orders, b.orders);
assert.notEqual(a.orders, 'ecoScreenV2.orders');
member = { ...member, role: 'Sales' };
await initializeSession();
assert.equal(identity.user, null, 'Non-admin email login denied');
assert.match(identity.error, /Owner\/Admin/);
member = null;
await initializeSession();
assert.equal(identity.user, null);
assert.equal(identity.companyId, '');
await assert.rejects(authenticatedHeaders());
token = null;
await initializeSession();
assert.equal(identity.user, null);
await assert.rejects(authenticatedHeaders());
globalThis.window = {};
globalThis.fetch = async url => {
  assert.equal(url, '/api/staff-session');
  return new Response(JSON.stringify({ user: { userId: 'legacy-installer', role: 'Installer', name: 'Installer' }, companyId: 'company', mode: 'pin' }));
};
await initializeSession();
assert.equal(identity.mode, 'pin');
assert.equal(identity.user.userId, 'legacy-installer');
assert.equal(identity.user.role, 'Installer');
assert.equal((await authenticatedHeaders())['X-CRM-Request'], '1');
assert.equal((await authenticatedHeaders()).Authorization, undefined);
assert.equal(canIdentityWriteCloudCollection('installationJobs'), true);
assert.equal(canIdentityWriteCloudCollection('orders'), true);
assert.equal(canIdentityWriteCloudCollection('productionJobs'), true);
assert.equal(canIdentityWriteCloudCollection('warrantyCards'), true);
assert.equal(canIdentityWriteCloudCollection('quotations'), false);
assert.equal(canIdentityWriteCloudCollection('users'), false);
identity.user.role = '  Production  ';
assert.equal(canIdentityWriteCloudCollection('productionJobs'), true);
assert.equal(canIdentityWriteCloudCollection('orders'), true);
assert.equal(canIdentityWriteCloudCollection('installationJobs'), false);
assert.equal(canIdentityWriteCloudCollection('quotations'), false);
identity.user.role = 'Installer';
const installerWrites = [];
globalThis.fetch = async (url, options = {}) => {
  assert.ok(String(url).startsWith('/api/staff-data?collection='));
  const collection = new URL(String(url), 'https://crm.test').searchParams.get('collection');
  if ((options.method || 'GET') === 'POST') {
    installerWrites.push(collection);
    return new Response(JSON.stringify({ ok: true }), { status: 200, headers: { 'content-type': 'application/json' } });
  }
  return new Response('[]', { status: 200, headers: { 'content-type': 'application/json' } });
};
const localSnapshot = Object.fromEntries(cloudCollections.map((collection) => [collection, [{ id: `${collection}-local`, updatedAt: '2026-09-14T00:00:00.000Z' }]]));
const installerSync = await safeSyncWithCloud(localSnapshot, { backupWriter: async () => true });
assert.equal(installerSync.ok, true);
assert.deepEqual(installerWrites.sort(), ['installationJobs', 'orders', 'productionJobs', 'warrantyCards'].sort());
assert.deepEqual(installerSync.snapshot.quotations, []);
assert.deepEqual(installerSync.snapshot.users, []);
await supabase.auth.dispose();
console.log('Auth: verified membership identity, current access token, expired/no-membership denial, and isolated cache keys.');
