import assert from 'node:assert/strict';
const { runtimeEnv } = await import('../src/env.js');
runtimeEnv.VITE_SUPABASE_URL = 'https://test.example.invalid';
runtimeEnv.VITE_SUPABASE_ANON_KEY = 'test-public-key';
const { supabase, identity, initializeSession, authenticatedHeaders } = await import('../src/session.js');
const user = { id: '11111111-1111-4111-8111-111111111111', email: 'test@example.invalid' };
let member = { company_id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', role: 'Sales', display_name: 'Test', staff_user_id: 'old-staff-id' };
let token = 'user-token';
supabase.auth.getSession = async () => ({ data: { session: token ? { access_token: token, user } : null }, error: null });
supabase.auth.getUser = async () => ({ data: { user }, error: null });
globalThis.fetch = async (url, options) => {
  assert.ok(String(url).includes('user_id=eq.' + user.id));
  assert.ok(String(url).includes('active=eq.true'));
  const headers = new Headers(options.headers);
  assert.equal(headers.get('Authorization'), 'Bearer ' + token);
  return new Response(JSON.stringify(member), { status: 200, headers: { 'content-type': 'application/json' } });
};
await initializeSession();
assert.equal(identity.companyId, member.company_id);
assert.equal(identity.user.userId, 'old-staff-id');
assert.equal(identity.user.role, 'Sales');
const a = (await import('../src/storage.js?companyA')).storageKeys;
token = 'refreshed-user-token';
assert.equal((await authenticatedHeaders()).Authorization, 'Bearer refreshed-user-token');
member = { ...member, company_id: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb' };
await initializeSession();
const b = (await import('../src/storage.js?companyB')).storageKeys;
assert.notEqual(a.orders, b.orders);
assert.notEqual(a.orders, 'ecoScreenV2.orders');
member = null;
await initializeSession();
assert.equal(identity.user, null);
assert.equal(identity.companyId, '');
await assert.rejects(authenticatedHeaders());
token = null;
await initializeSession();
assert.equal(identity.user, null);
await assert.rejects(authenticatedHeaders());
supabase.auth.stopAutoRefresh();
console.log('Auth: verified membership identity, current access token, expired/no-membership denial, and isolated cache keys.');
