import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db = new PGlite();
await db.exec(`create role anon; create role authenticated; create schema auth;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
grant usage on schema auth,public to authenticated,anon; grant execute on function auth.uid() to authenticated,anon;
create table public.crm_v2_sync(collection text primary key,data jsonb not null default '[]',updated_at timestamptz default now());
alter table public.crm_v2_sync enable row level security;
grant all on public.crm_v2_sync to anon,authenticated;
create policy old_open_policy on public.crm_v2_sync for all using (true) with check (true);
insert into public.crm_v2_sync(collection,data) values ('orders','[{"id":"preserved-order"}]');`);
await db.exec(await readFile(new URL('../supabase/migrations/20260908032359_v2_auth_company_lead_radar.sql', import.meta.url),'utf8'));
const a = (await db.query('select id from crm_v2_companies')).rows[0].id;
const b = '22222222-2222-4222-8222-222222222222';
const u = '11111111-1111-4111-8111-111111111111';
const v = '33333333-3333-4333-8333-333333333333';
const w = '44444444-4444-4444-8444-444444444444';
await db.exec(`insert into auth.users values ('${u}'),('${v}'),('${w}');
insert into crm_v2_companies values ('${b}','Company B');
insert into crm_v2_memberships(user_id,company_id,role,display_name) values ('${u}','${a}','Boss','A'),('${v}','${b}','Sales','B');
insert into crm_v2_sync(company_id,collection,data) values ('${b}','orders','[{"id":"B-order"}]');`);
let checks = 0;
async function asUser(user = u, role = 'authenticated') { await db.exec(`reset role; set role ${role}; select set_config('request.jwt.claim.sub','${user}',false);`); }
async function denied(sql) { await assert.rejects(db.exec(sql)); checks++; }
await asUser();
assert.equal((await db.query('select * from crm_v2_sync')).rows.length,1); checks++;
assert.equal((await db.query('select data from crm_v2_sync')).rows[0].data[0].id,'preserved-order'); checks++;
assert.equal((await db.query('select * from crm_v2_memberships')).rows.length,1); checks++;
await denied(`update crm_v2_memberships set role='Admin' where user_id='${u}'`);
await denied(`insert into crm_v2_sync(company_id,collection) values ('${b}','stolen')`);
await denied(`update crm_v2_sync set company_id='${b}' where company_id='${a}'`);
await db.exec(`insert into crm_v2_prospects(company_id,name,prospect_type,classification,total_score) values ('${a}','A lead','customer','hot',80)`); checks++;
const id = (await db.query('select id from crm_v2_prospects')).rows[0].id;
await db.exec(`update crm_v2_prospects set contact_status='replied',do_not_contact=true where id='${id}'`); checks++;
await denied(`update crm_v2_prospects set company_id='${b}' where id='${id}'`);
await denied(`insert into crm_v2_prospects(company_id,name,prospect_type,classification) values ('${b}','bad','customer','hot')`);
await denied(`insert into crm_v2_prospects(company_id,name,prospect_type,classification) values ('${a}','bad','invalid','hot')`);
await denied(`update crm_v2_prospects set total_score='NaN' where id='${id}'`);
await denied(`delete from crm_v2_prospects where id='${id}'`);
await asUser(v);
assert.equal((await db.query('select * from crm_v2_prospects')).rows.length,0); checks++;
assert.equal((await db.query(`update crm_v2_prospects set name='stolen' where id='${id}' returning id`)).rows.length,0); checks++;
await asUser(w);
assert.equal((await db.query('select * from crm_v2_sync')).rows.length,0); checks++;
await denied(`insert into crm_v2_prospects(company_id,name,prospect_type,classification) values ('${a}','bad','customer','hot')`);
await db.exec(`reset role; update crm_v2_memberships set active=false where user_id='${u}'`);
await asUser();
assert.equal((await db.query('select * from crm_v2_sync')).rows.length,0); checks++;
assert.equal((await db.query('select * from crm_v2_prospects')).rows.length,0); checks++;
await asUser('', 'anon');
for (const table of ['crm_v2_companies','crm_v2_memberships','crm_v2_sync','crm_v2_prospects']) await denied(`select * from ${table}`);
await db.close();
console.log(`RLS: ${checks} actual PostgreSQL allow/deny checks passed; legacy order retained.`);
